# Generated by Django 4.1.9 on 2023-05-26 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                ("created", models.DateTimeField(auto_now_add=True)),
                ("id", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.account")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Context",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("text", models.TextField()),
                ("account", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="chatbot.account")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
