# Generated by Django 4.1.9 on 2023-06-02 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_question_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="body",
            new_name="request",
        ),
    ]
