OKAY_SYNONYMS = [
    "A-OK",
    "Hunky-dory",
    "Cool beans",
    "Groovy",
    "Jellybean",
    "Smashing",
    "Swell",
    "Super-duper",
    "Bob's your uncle",
    "Hunky-dory",
    "Righty-o",
    "No worries, mate",
    "Piece of cake",
    "Smooth as a baby's bottom",
    "Fine and dandy",
    "A-OK",
    "In the bag",
    "Like a boss",
    "Radical",
    "Awesome sauce",
    "Alrighty then",
    "Jolly good",
    "Satisfactory",
    "Saved in the secret squirrel vault",
    "Stashed away in the mystical sock drawer",
    "Securely hidden in the abyss of forgotten memories",
    "Bottled up in the bottomless jar of eternal procrastination",
]

TOP_ENGLISH_WORDS = [
    "the",
    "be",
    "to",
    "of",
    "and",
    "a",
    "in",
    "that",
    "have",
    "i",
    "it",
    "for",
    "not",
    "on",
    "with",
    "he",
    "as",
    "you",
    "do",
    "at",
    "this",
    "but",
    "his",
    "by",
    "from",
    "they",
    "we",
    "say",
    "her",
    "she",
    "or",
    "an",
    "will",
    "my",
    "one",
    "all",
    "would",
    "there",
    "their",
    "what",
    "so",
    "up",
    "out",
    "if",
    "about",
    "who",
    "get",
    "which",
    "go",
    "me",
]

QUESTION_SENTENCE_STARTS = [
    "can i",
    "how do",
    "what is",
    "is it",
    "are you",
    "do i",
    "will you",
    "should i",
    "did you",
    "could you",
    "would you",
    "where can",
    "when will",
    "why does",
    "who is",
    "which one",
    "have you",
    "has she",
    "can we",
    "did they",
    "would it",
    "should we",
    "are there",
    "is there",
    "how can",
    "what are",
    "do you",
    "can you",
    "will it",
    "should i",
    "did he",
    "could i",
    "would she",
    "where should",
    "when can",
    "why did",
    "who will",
    "which one",
    "have they",
    "has it",
    "can i",
    "how do",
    "what is",
    "is it",
    "are you",
    "do i",
    "will you",
    "should i",
    "did you",
    "could you",
    "would you",
    "where can",
    "when will",
    "why does",
    "who is",
    "which one",
    "have you",
    "has she",
    "can we",
    "did they",
    "would it",
    "should we",
    "are there",
    "is there",
    "how can",
    "what are",
    "do you",
    "can you",
    "will it",
    "should i",
    "did he",
    "could i",
    "would she",
    "where should",
    "when can",
    "why did",
    "who will",
    "which one",
    "have they",
    "has it",
    "can i",
    "how do",
    "what is",
    "is it",
    "are you",
    "do i",
    "will you",
    "should i",
    "did you",
    "could you",
    "would you",
    "where can",
    "when will",
    "why does",
    "who is",
    "which one",
    "have you",
    "has she",
    "can we",
    "did they",
    "would it",
    "should we",
    "are there",
    "is there",
    "how can",
    "what are",
    "do you",
    "can you",
    "will it",
    "should i",
    "did he",
    "could i",
    "would she",
    "where should",
    "when can",
    "why did",
    "who will",
    "which one",
    "have they",
    "has it",
]
